---
  title: "TDA - Time Series"
output:
  html_document: default
word_document: default
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Libraries
```{r}
#ODE 
library(deSolve)

#Graphs and data Manipulation
library(tidyverse)
library(data.table)

#Confusion Matrix
library(caret) 

#Persistent Homology
library(nonlinearTseries)
library(TDAstats)

#BettiNumbers
library(matrixStats)
```



#Aperiodic 
```{r}
Time_Series_Data<- data.frame()
for (i in 1:200){
  parameters2 <- c(b = 7.48, c_ea = 0.009, c_pa = 0.004, c_el = 0.012, u_p = 0, u_l = 0.267, u_a = 0.96)
  state2 <- c(L = sample(2:100,1), P = sample(2:100,1), A = sample(2:100,1))
  beetles2<-function(t, state, parameters) {
    with(as.list(c(state, parameters)),{
      # rate of change
      L1 <- b * A * exp((-c_el * L) - (c_ea * A))
      P1 <- L * (1 - u_l) 
      A1 <- (P * exp(-c_pa * A) + A * (1 - u_a)) 
      
      # return the rate of change
      list(c(L1, P1, A1))
    }) # end with(as.list ...
  }
  
Aperiodic_i <- ode(y = state2, times = seq(0, 200), func = beetles2, parms = parameters2, method = "iteration")
  

aperiodic <- as.data.frame(Aperiodic_i) %>% select(A)
transposeAperiodic<-t(aperiodic)
Time_Series_Data <- rbind.data.frame(transposeAperiodic,Time_Series_Data)  
}
```



#Stable Equilibrium - Time series
```{r}
for (i in 1:200){
  parameters1 <- c(b = 7.48, c_ea = 0.009, c_pa = 0.004, c_el = 0.012, u_p = 0, u_l = 0.267, u_a = 0.73)

  state1 <- c(L = sample(2:100,1), P = sample(2:100,1), A = sample(2:100,1))
  
  #ODE's that model Beetles
  beetles1<-function(t, state, parameters) {
    with(as.list(c(state, parameters)),{
      # rate of change
      L1 <- b * A * exp((-c_el * L) - (c_ea * A))
      P1 <- L * (1 - u_l) 
      A1 <- (P * exp(-c_pa * A) + A * (1 - u_a)) 
      
      # return the rate of change
      list(c(L1, P1, A1))
    }) # end with(as.list ...
  }

  #Plotting A vs Time Graph
  
  Stable_i <- ode(y = state1, times = seq(0, 200), func = beetles1, parms = parameters1, method = "iteration")
  
#Time_Series_Stable1 <- rbind.data.frame(Time_Series_Stable,Time_Series_Stable1)
stable <- as.data.frame(Stable_i) %>% select(A)
transposeStable<-t(stable)
Time_Series_Data <- rbind.data.frame(transposeStable,Time_Series_Data)
}
```



#Rename rows so we can Identify Time series as Stable or Aperiodic
```{r}
(setattr(Time_Series_Data, "row.names", c(rep("Stable",200),rep("Aperiodic",200))))
```


#K-Means
```{r}
set.seed(250)
kmtotal <- kmeans(Time_Series_Data, 2, iter.max = 10, nstart = 1)
```


#ConfusionMatrix
```{r}
km_clusters <- kmtotal$cluster
correct <- rep(c("2","1"), each=200)
cfm <- table(correct,km_clusters)
cfm
```


#Analysis
```{r}
TP <- cfm[1,1]
FN <- cfm[1,2]
FP <- cfm[2,1]
TN <- cfm[2,2]

Recall <- TP/(TP+FN)
Specificity <- TN/(TN+FP)
Precision <- TP/(TP+FP)
Negative_predictive_value <- TP/(TP+FP)
Fall_out <- FP/(FP+TN)
False_discovery_rate <- FP/(FP+TP)
Accuracy <- (TP+TN)/(TP+TN+FP+FN)
F1_Score <- (2*TP)/((2*TP)+FP+FN)
MCC <- (TP*TN-FP*FN)/sqrt((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
```

#for loop select rows one by one and gets their persistence diagram
```{r}
pers <- data.frame()
for (i in 1:400){
x<- data.matrix(Time_Series_Data[i,])
a<- buildTakens(x,2,3)
hom <- calculate_homology(a,return_df = TRUE)
hom <- hom %>%
  mutate(persistence = death-birth) %>%
  mutate(persistent = ifelse(persistence > max(persistence)-0.00001, 1,0))
hom_matrix <- data_frame(hom) %>% select(dimension, persistent)
hom_matrix <- as.data.frame(hom_matrix) 
p1 <- hom_matrix[hom_matrix$persistent == '1',] 

pers <- rbind.data.frame(pers,p1) 
}
```


```{r}
#BettiNumbers

```
